version: '3.3'
services:
  unifi:
    container_name: unifi
    restart: always
    volumes:
      - '$DOCKERPATH/UniFi:/config'
    environment:
      - PUID=1000
      - PGID=1000
    networks:
      lan:
        ipv4_address: $IP
    image: linuxserver/unifi-controller:latest
networks:
  lan:
    external: true